# Generated by Django 6.0.3 on 2026-04-01 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('about_restaurant', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('has_top_offers', models.BooleanField(default=False)),
                ('default_opening_hour', models.TimeField(default='18:00')),
                ('default_closing_hour', models.TimeField(default='01:00')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60)),
                ('allow_advance_booking_days', models.PositiveIntegerField(default=60)),
                ('cool_down', models.PositiveIntegerField(default=30)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('seating_types', models.ManyToManyField(blank=True, to='Restaurants.seatingtype')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('closed_full_day', models.BooleanField(default=False)),
                ('adjusted_opening_hour', models.IntegerField(blank=True, null=True)),
                ('adjusted_closing_hour', models.IntegerField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='TableSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField()),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('price_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('additional_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'unique_together': {('capacity', 'size')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('is_combinable', models.BooleanField(default=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='Restaurants.restaurant')),
                ('seating_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurants.seatingtype')),
                ('table_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='Restaurants.tablesize')),
            ],
            options={
                'unique_together': {('restaurant', 'name')},
            },
        ),
    ]
