# Generated by Django 6.0.3 on 2026-04-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0003_specialday_name_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Restaurants/media/images/'),
        ),
    ]
