# Generated by Django 6.0.3 on 2026-04-01 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_reviewsummary_testimonials_favouriterestaurant'),
        ('UsersHandling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantstaff',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurantstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
