# Generated by Django 6.0.3 on 2026-04-02 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersHandling', '0002_alter_restaurantstaff_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='tier',
            field=models.CharField(choices=[('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple')], default='Purple', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurantstaff',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
