# Generated by Django 6.0.3 on 2026-04-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersHandling', '0003_alter_customerprofile_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='UsersHandling/media/images/'),
        ),
    ]
